server:
  port: 8002


spring:
  application:
    name: restaurant-provider-waiter
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=UTC
    username: root
    password: li1234567
eureka:
  client:
    register-with-eureka: true #表示是否向注册中心注册自己
    fetchRegistry:  true #是否从eurekaserver抓取已有的注册信息，默认为true，单节点无所谓，集群必须配置为true
    service-url: #监控页面
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      defaultZone: http://localhost:7001/eureka #单机版

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.order.restaurant.entities
  configuration:
    map-underscore-to-camel-case: true